'use strict';
const $ = id => document.getElementById(id);
const escapeHtml = s => String(s ?? '').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const field = (p,k,title,value='',wide=false) => `<label class="${wide?'wide':''}">${title}<input id="${p}-${k}" maxlength="300" value="${escapeHtml(value)}"></label>`;
const amount = (p,k,title,value='') => `<label>${title}<input id="${p}-${k}" type="number" min="0" max="1000000000" step="0.01" inputmode="decimal" value="${value}" placeholder="Unknown"></label>`;
function packageForm(p,name){return `<fieldset><legend>${name}</legend><div class="field-grid">${field(p,'name','Booking name',name,true)}${field(p,'deliverables','Creator uploads / content', '',true)}${amount(p,'fee','Quoted fee')}${amount(p,'other','Other known costs')}</div>${['rights','edits'].map(k=>`<div class="cost-group"><div><label>${k==='rights'?'Paid-use rights':'Edited versions'}<select id="${p}-${k}-status"><option value="unknown">Unconfirmed</option><option value="included">Included in quoted fee</option><option value="extra">Additional charge</option><option value="unused">Not required</option></select></label><div class="conditional" id="${p}-${k}-amount-wrap" hidden>${amount(p,k+'-cost','Additional cost')}</div></div></div>`).join('')}<details class="scope"><summary>Audience, usage terms and release plan</summary><div class="field-grid">${field(p,'markets','Audience markets / evidence','',true)}${field(p,'views','Estimated views / evidence','',true)}${field(p,'term','Paid-use term')}${field(p,'platforms','Paid-use platforms')}${field(p,'territories','Usage territories')}${field(p,'permissions','Editing permissions')}${field(p,'exclusivity','Exclusivity terms','',true)}${field(p,'timing','Release dates / approval deadline','',true)}${field(p,'measurement','Success measure / reporting date','',true)}</div></details></fieldset>`}
$('packages').innerHTML=packageForm('a','Booking A')+packageForm('b','Booking B');
const keys=['name','deliverables','fee','other','rights-status','rights-cost','edits-status','edits-cost','markets','views','term','platforms','territories','permissions','exclusivity','timing','measurement'];
const sample={a:{name:'Booking A',deliverables:'One YouTube upload',fee:'4000',other:'0','rights-status':'extra','rights-cost':'1500','edits-status':'extra','edits-cost':'750',markets:'UK audience share: evidence requested',views:'Supplier estimate: evidence requested',term:'30 days',platforms:'YouTube ads',territories:'UK',permissions:'Three edited versions; final edits approved by creator',exclusivity:'Unconfirmed',timing:'Upload date and review deadline to agree',measurement:'App installs; attribution and report date to agree'},b:{name:'Booking B',deliverables:'One YouTube upload',fee:'6000',other:'0','rights-status':'included','rights-cost':'','edits-status':'included','edits-cost':'',markets:'UK audience share: evidence requested',views:'Supplier estimate: evidence requested',term:'30 days',platforms:'YouTube ads',territories:'UK',permissions:'Three edited versions; final edits approved by creator',exclusivity:'Unconfirmed',timing:'Upload date and review deadline to agree',measurement:'App installs; attribution and report date to agree'}};
let exampleMode=true;
let containsExample=true;
function numeric(id){const el=$(id);const raw=el.value.trim();const invalid=!el.disabled&&(el.validity.badInput || el.validity.stepMismatch || el.validity.rangeUnderflow || el.validity.rangeOverflow || (raw!==''&&(!Number.isFinite(Number(raw))||Number(raw)<0||Number(raw)>1e9)));el.setAttribute('aria-invalid',String(invalid));let hint=$(id+'-error');if(!hint){hint=document.createElement('span');hint.id=id+'-error';hint.className='field-error';el.after(hint);el.setAttribute('aria-describedby',hint.id)}hint.textContent=invalid?(id==='target-cpi'?'Use a positive amount with up to two decimal places.':'Use 0 or above, with up to two decimal places.') : '';hint.hidden=!invalid;return {value:raw===''?null:Number(raw),invalid};}
function money(n){return new Intl.NumberFormat('en-GB',{style:'currency',currency:$('currency').value,maximumFractionDigits:2}).format(n)}
function read(p){const data={};keys.forEach(k=>data[k]=$(`${p}-${k}`).value.trim());let invalid=false,total=0,unknown=[];
 for(const [k,label] of [['fee','Quoted fee'],['other','Other campaign costs']]){const n=numeric(`${p}-${k}`);invalid ||= n.invalid;if(n.value===null)unknown.push(label);else total+=Math.round(n.value*100)/100;}
 for(const [k,label] of [['rights','Paid-use rights'],['edits','Edited versions']]){const state=data[k+'-status'];$(`${p}-${k}-amount-wrap`).hidden=state!=='extra';if(state==='unknown')unknown.push(label);if(state==='extra'){const n=numeric(`${p}-${k}-cost`);invalid ||=n.invalid;if(n.value===null)unknown.push(label+' charge');else total+=Math.round(n.value*100)/100;}}
 const questions=[];unknown.forEach(k=>questions.push(`Confirm ${k.toLowerCase()}.`));
 const gaps={deliverables:'Which uploads and content pieces are included?',markets:'What share of the audience is in your target markets, and what supports it?',views:'What supports the view estimate?',exclusivity:'What exclusivity is included, and for how long?',timing:'When will the draft, feedback and final upload happen?',measurement:'Which outcome will be reported, under what attribution rules and on what date?'};
 if(data['rights-status']!=='unused')Object.assign(gaps,{term:'How long can the video be used in ads?',platforms:'Which advertising platforms are covered?',territories:'Which usage territories are covered?'});
 if(data['rights-status']!=='unused'||data['edits-status']!=='unused')gaps.permissions='Which changes or edited versions can you make?';
 for(const [k,q] of Object.entries(gaps))if(!data[k]||/unconfirmed|requested|to agree/i.test(data[k]))questions.push(q);
 return {data,total,unknown,questions,invalid};}
function all(){return ['a','b'].map(read)}
function update(){const rows=all();const isInstalls=$('objective').value==='installs';$('target-cpi').disabled=!isInstalls;const cpi=numeric('target-cpi');const cpiInvalid=isInstalls&&(cpi.invalid||(cpi.value!==null&&cpi.value<=0));$('target-cpi').setAttribute('aria-invalid',String(cpiInvalid));const invalid=rows.some(r=>r.invalid)||cpiInvalid;$('cpi-note').textContent=isInstalls?'':'The install calculation is hidden for this objective. Use the agreed purchase, subscription or launch measures in your proposal discussion.';
 $('form-warning').hidden=!invalid;$('print').disabled=invalid;$('csv').disabled=invalid;
 $('mode-note').textContent=containsExample?'This worksheet started with hypothetical example values. Confirm or replace every entry before using it for a real booking.':'Your worksheet. Missing amounts and terms remain open questions.';
 $('report').innerHTML='<div class="report-grid">'+rows.map((r,i)=>`<article class="report-card"><h3>${escapeHtml(r.data.name||`Booking ${i?'B':'A'}`)}</h3><div class="total">${r.invalid?'Check amounts':money(r.total)}</div><p class="status">${r.unknown.length?'KNOWN COST SO FAR · INCOMPLETE':'TOTAL ENTERED COST'}</p><p>${escapeHtml(r.data.deliverables||'Content deliverables need confirming.')}</p>${isInstalls&&cpi.value>0&&!cpiInvalid&&!r.invalid?`<p><strong>${Math.ceil(Math.round(r.total*100)/Math.round(cpi.value*100)).toLocaleString('en-GB')} installs required${r.unknown.length?' at this known cost':''}</strong><br>${money(r.total)} ÷ ${money(cpi.value)} target CPI, rounded up.${r.unknown.length?' Missing charges would raise this requirement.':''}</p>`:''}<h4>${r.questions.length?'Questions before booking':'All worksheet fields are filled'}</h4>${r.questions.length?'<ul>'+r.questions.map(q=>'<li>'+escapeHtml(q)+'</li>').join('')+'</ul>':'<p>Check the supplied evidence and confirm that the terms meet your campaign needs.</p>'}</article>`).join('')+'</div>';
 return {rows,invalid};}
function load(blank){for(const p of ['a','b'])for(const k of keys)$(`${p}-${k}`).value=blank?(k.endsWith('-status')?'unknown':k==='name'?`Booking ${p.toUpperCase()}`:''):sample[p][k]||'';$('campaign-name').value=blank?'':'Example mobile game campaign';$('decision').value='';$('target-cpi').value='';$('currency').value='EUR';$('objective').value='installs';exampleMode=!blank;containsExample=!blank;$('export-status').textContent='';update();}
$('load-example').addEventListener('click',()=>{if(!exampleMode&&!confirm('Replace your current entries with the example? Download your worksheet first if you want to keep them.'))return;load(false)});
$('start-blank').addEventListener('click',()=>{if(!exampleMode&&!confirm('Clear your current entries? Download your worksheet first if you want to keep them.'))return;load(true);$('campaign-name').focus()});
document.querySelectorAll('input,select,textarea').forEach(el=>{el.addEventListener('input',()=>{exampleMode=false;update()});el.addEventListener('change',()=>{exampleMode=false;update()})});
const titles={deliverables:'Content deliverables',fee:'Quoted fee',other:'Other known costs','rights-status':'Paid-use rights','rights-cost':'Additional rights cost','edits-status':'Edited versions','edits-cost':'Additional editing cost',markets:'Audience markets / evidence',views:'View estimate / evidence',term:'Usage term',platforms:'Usage platforms',territories:'Usage territories',permissions:'Editing permissions',exclusivity:'Exclusivity',timing:'Release and approval dates',measurement:'Measurement and reporting'};
const statusNames={included:'Included in quoted fee',extra:'Additional charge',unused:'Not required',unknown:'Unconfirmed'};
function exportRows(rows){const result=[['Campaign',$('campaign-name').value||'Untitled campaign',''],['Currency',$('currency').value,''],['Objective',$('objective').selectedOptions[0].text,''],['Values',containsExample?'Started from hypothetical example; verify all values':'Entered by user',''],['Field',rows[0].data.name||'Booking A',rows[1].data.name||'Booking B']];
 for(const [k,label]of Object.entries(titles))result.push([label,...rows.map(r=>{if(k.endsWith('-cost')&&r.data[k.replace('-cost','-status')]!=='extra')return r.data[k.replace('-cost','-status')]==='unknown'?'Unconfirmed':'No additional charge entered';return statusNames[r.data[k]]||r.data[k]||'Unknown'})]);
 result.push(['Known total',...rows.map(r=>money(r.total)+(r.unknown.length?' (incomplete)':''))]);
 const cpi=Number($('target-cpi').value);if($('objective').value==='installs'&&cpi>0){result.push(['Target CPI',money(cpi),money(cpi)]);result.push(['Installs required from known cost',...rows.map(r=>String(Math.ceil(Math.round(r.total*100)/Math.round(cpi*100)))+(r.unknown.length?' (costs incomplete)':''))]);}
 result.push(['Open questions',...rows.map(r=>r.questions.join('\n')||'Check supplied evidence and terms.')]);result.push(['Decision / approval conditions',$('decision').value||'Not yet recorded','']);return result;}
function csvCell(value){let s=String(value);if(/^[\s]*[=+\-@\t\r]/.test(s))s="'"+s;return '"'+s.replace(/"/g,'""')+'"'}
$('csv').addEventListener('click',()=>{const {rows,invalid}=update();if(invalid)return;const csv='\uFEFF'+exportRows(rows).map(row=>row.map(csvCell).join(',')).join('\r\n');const url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='arch-creator-quote-worksheet.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);$('export-status').textContent='Worksheet downloaded. Open the CSV in Excel or Google Sheets.'});
function preparePrint(){const {rows,invalid}=update();if(invalid){$('print-report').innerHTML='<h1>Check the worksheet amounts</h1><p>The current entries contain invalid amounts. Correct them before exporting a comparison.</p>';return false;}const data=exportRows(rows);$('print-report').innerHTML='<h1>ARCH. Creator quote comparison</h1><p>'+escapeHtml($('campaign-name').value||'Untitled campaign')+'</p><p>'+(containsExample?'Started from a hypothetical example. Verify every value before using this for a real booking.':'Prepared from the values entered in this worksheet.')+' Costs are in '+escapeHtml($('currency').value)+'. Check tax treatment and any omitted charges.</p><table><tbody>'+data.map((r,i)=>'<tr>'+r.map(v=>`<${i===4?'th':'td'}>${escapeHtml(v)}</${i===4?'th':'td'}>`).join('')+'</tr>').join('')+'</tbody></table><p>Cost comparisons do not predict creator performance. Required installs use your target CPI; actual attribution and payback need separate evidence.</p>';return true;}
$('print').addEventListener('click',()=>{if(preparePrint())window.print()});window.addEventListener('beforeprint',preparePrint);load(false);
